name: Deploy Vite App to Azure

on:
  push:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Specify the Node.js version you need

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Set environment variables for the build
      - name: Set environment variables for Vite build
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}  # Use the VITE_API_URL secret from GitHub Secrets
        run: |
          # Optional: You can print the value to verify the environment variable is set
          echo "VITE_API_URL=$VITE_API_URL"
          npm run build  # Run the Vite build process

      # Step 5: Deploy to Azure
      - name: Deploy to Azure
        uses: Azure/webapps-deploy@v2
        with:
          app-name: '<YOUR-AZURE-APP-NAME>'  # Replace with your Azure app name
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}  # Use Azure publish profile secret
